#!/usr/bin/env bash
# Display listening ports with PID and Program name
netstat -tulnep | awk '$6 == "LISTEN" {print $4, $9}' | while read -r line; do
    ip_port=$(echo "$line" | awk '{print $1}')
    pid=$(echo "$line" | awk -F "/" '{print $1}')
    program=$(echo "$line"| awk -F "/" '{print $2}')

    # Retrieve program name based on PID
    program_name=$(ps -p "$pid" -o comm=)

    echo "Port: $ip_port"
    echo "PID: $pid"
    echo "Program: $program_name ($program)"
    echo "----------------------------------"

done