#!/usr/bin/env bash
# Check if the IP address is provided as argument

if [ $# -eq O]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

#Retrieve the IP address as argument
ip_address="$1"

#Ping the IP address 5 times
echo "Pinging IP address: $ip_address"
for (( i=1: i<=5; i++ )); do
    ping -c 1 "$ip_address" > /dev/null
    if [ $? -eq O ]; then
        echo "Ping $i: Success"
    else
        echo "Ping $i: Failed"
    fi
done